// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TD1.Models;

#nullable disable

namespace TD1.Migrations
{
    [DbContext(typeof(ProduitsDBContext))]
    [Migration("20241004082727_CreationBD2")]
    partial class CreationBD2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TD1.Models.Marque", b =>
                {
                    b.Property<int>("IdMarque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idmarque");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMarque"));

                    b.Property<string>("NomMarque")
                        .HasColumnType("text")
                        .HasColumnName("nommarque");

                    b.HasKey("IdMarque")
                        .HasName("pk_marque");

                    b.ToTable("marque");
                });

            modelBuilder.Entity("TD1.Models.Produit", b =>
                {
                    b.Property<int>("IdMarque")
                        .HasColumnType("integer")
                        .HasColumnName("idmarque");

                    b.Property<int>("IdTypeProduit")
                        .HasColumnType("integer")
                        .HasColumnName("idtypeproduit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("IdProduit")
                        .HasColumnType("integer")
                        .HasColumnName("idproduit");

                    b.Property<string>("NomPhoto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idnomphoto");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomproduit");

                    b.Property<int>("StockMax")
                        .HasColumnType("integer")
                        .HasColumnName("stockmax");

                    b.Property<int>("StockMin")
                        .HasColumnType("integer")
                        .HasColumnName("stockmin");

                    b.Property<int>("StockReel")
                        .HasColumnType("integer")
                        .HasColumnName("stockreel");

                    b.Property<string>("UriPhoto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("iduriproduit");

                    b.Property<int?>("idmarque")
                        .HasColumnType("integer");

                    b.Property<int?>("idtypeproduit")
                        .HasColumnType("integer");

                    b.HasKey("IdMarque", "IdTypeProduit")
                        .HasName("pk_produit");

                    b.HasIndex("idmarque");

                    b.HasIndex("idtypeproduit");

                    b.ToTable("produit", t =>
                        {
                            t.Property("idmarque")
                                .HasColumnName("idmarque1");

                            t.Property("idtypeproduit")
                                .HasColumnName("idtypeproduit1");
                        });
                });

            modelBuilder.Entity("TD1.Models.TypeProduit", b =>
                {
                    b.Property<int>("IdTypeProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idtypeproduit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeProduit"));

                    b.Property<string>("NomTypeProduit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomtypeproduit");

                    b.HasKey("IdTypeProduit")
                        .HasName("pk_typeproduit");

                    b.ToTable("typeproduit");
                });

            modelBuilder.Entity("TD1.Models.Produit", b =>
                {
                    b.HasOne("TD1.Models.Marque", "IdmarqueNavigation")
                        .WithMany("Produits")
                        .HasForeignKey("idmarque")
                        .HasConstraintName("fk_produit_marque");

                    b.HasOne("TD1.Models.TypeProduit", "IdtypeProduitNavigation")
                        .WithMany("Produits")
                        .HasForeignKey("idtypeproduit")
                        .HasConstraintName("fk_produit_typeproduit");

                    b.Navigation("IdmarqueNavigation");

                    b.Navigation("IdtypeProduitNavigation");
                });

            modelBuilder.Entity("TD1.Models.Marque", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("TD1.Models.TypeProduit", b =>
                {
                    b.Navigation("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
